### ISSUE TITLE
SSH fails with invalid format message

### ISSUE THREAD

**Issue by tspascoal** [mgbowen/windows-fido-bridge#10]
Hi,

I can't use the generated key to log with ssh (There are no problems generating the key)

Installed the bridge via apt-get on `Debian GNU/Linux bullseye/sid` and running ssh `OpenSSH_8.4p1 Debian-5, OpenSSL 1.1.1j  16 Feb 2021`

Yubikey neo with firmware `3.3.0`
Also tried with a more recent Yubikey 5 with firmware `5.1.2`

Both have the same exact results

Keys have 600 permission for the private key and 644 for the pub key

When trying to call with ssh  (used `-T` for testing it) it fails with the error

```
sign_and_send_pubkey: signing failed for ECDSA-SK "/home/tspascoal/.ssh/id_ecdsa_sk": invalid format
```

When doing the same with `-vvvT` 

I get this (relevant snippet I believe) from the logs

```
debug1: Offering public key: /home/tspascoal/.ssh/id_ecdsa_sk ECDSA-SK SHA256:REDACTED   authenticator
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /home/tspascoal/.ssh/id_ecdsa_sk ECDSA-SK SHA256:REDACTED  authenticator
debug3: sign_and_send_pubkey: ECDSA-SK SHA256:REDACTED
debug3: sign_and_send_pubkey: signing using sk-ecdsa-sha2-nistp256@openssh.com SHA256:REDACTED
Confirm user presence for key ECDSA-SK SHA256:REDACTED
debug3: start_helper: started pid=790
debug3: ssh_msg_send: type 5
debug3: ssh_msg_recv entering
debug1: start_helper: starting /usr/lib/openssh/ssh-sk-helper
debug1: ssh-sk-helper: ready to sign with key ECDSA-SK, provider internal: msg len 280, compat 0x0
debug1: sshsk_sign: provider "internal", key ECDSA-SK, flags 0x01
debug1: sk_probe: 0 device(s) detected
debug1: ssh_sk_sign: failed to find sk
debug1: sshsk_sign: sk_sign failed with code -1
debug1: ssh-sk-helper: Signing failed: invalid format
debug1: ssh-sk-helper: reply len 8
debug3: ssh_msg_send: type 5
debug1: client_converse: helper returned error -4
debug3: reap_helper: pid=790
debug1: identity_sign: sshkey_sign: invalid format
sign_and_send_pubkey: signing failed for ECDSA-SK "/home/tspascoal/.ssh/id_ecdsa_sk": invalid format
```

There was no windows dialog to authorize the use of the key (like it happened when the key was generated)

The problem probably lies in this line  `debug1: sk_probe: 0 device(s) detected` line. (don't know if this generated by the helper or by the bridge though)

I've tried to generate with and without `-Oapplication=ssh:windows-fido-bridge-verify-required`

I've also defined env variables `WINDOWS_FIDO_BRIDGE_DEBUG=1` but doesn't seem to produce any extra output

Is there something I can do to diagnose the problem?

Thank you

P.S. I've tried with git for windows bash shell and this works fine as long as the shell is started with elevated privileges

**Comment by mgbowen** [comment]
How are you invoking SSH when trying to log in? This log line:

```
debug1: sshsk_sign: provider "internal", key ECDSA-SK, flags 0x01
```

Tells me that SSH isn't using windows-fido-bridge as its security key provider. Are you adding `-oSecurityKeyProvider=libwindowsfidobridge.so` (or setting `SecurityKeyProvider` in your ~/.ssh/config)?

**Comment by tspascoal** [comment]
Marvelous. This did the trick.

I was just using `SSH_SK_PROVIDER=/usr/lib/libwindowsfidobridge.so` I assumed it worked the same between `keygen` and `ssh` my bad for not following instructions.

Thank you
