### ISSUE TITLE
fatal error: span: No such file or directory

### ISSUE THREAD

**Issue by cysea** [mgbowen/windows-fido-bridge#15]
WSL2 Ubuntu 20.10 groovy

`$ make -j $(nproc)`

`...`

```
windows-fido-bridge/src/common/include/windows_fido_bridge/util.hpp:7:10: fatal error: span: No such file or directory
    7 | #include <span>
      |          ^~~~~~
compilation terminated.
```

**Comment by mgbowen** [comment]
Looks like groovy only includes g++-mingw version 9.3.0, which doesn't include `std::span` support. The minimum supported version for that is 10

I'm not terribly familiar with Ubuntu, so I'm not sure if there's a better way to get the latest version. I can try investigating some time later this week/weekend.

**Comment by cysea** [comment]
Solid research skills.

It's very likely that I've found the same link you did even before opening the issue -> upgraded from 20.04 (g++9.3.0) to 20.10 (g++10.3.0) -> still the same problem.

```
$ g++ --version

g++ (Ubuntu 10.3.0-1ubuntu1~20.10) 10.3.0
```

That's the only `g++` installed besides `g++9` and `g++10` which are probably aliases for different versions, unless you're referring to another compiler. I'm not really experienced with this.

**Comment by mgbowen** [comment]
From my original comment:

> Looks like groovy only includes g++-mingw version 9.3.0

I'm explicitly referring to [g++-mingw-w64](https://packages.ubuntu.com/groovy/g++-mingw-w64), which is version 9.3.0 in groovy. Presumably you need to upgrade to 21.04 to get `std::span` support.

**Comment by cysea** [comment]
```
$ g++-mingw-w64
g++-mingw-w64: command not found
```

Is there a way I can invoke it to check the version? What package should I be looking for so I could upgrade it?
