### ISSUE TITLE
Unsupported version 0x00050000 (supported: 0x00040000)?

### ISSUE THREAD

**Issue by schmitmd** [mgbowen/windows-fido-bridge#4]
Have you seen this error before?  Do you know what might be happening?  ...do I need to be running openssh 8.3+?

I see this error when running `SSH_SK_PROVIDER=/usr/local/lib/libwindowsfidobridge.so ssh-keygen -t ecdsa-sk`:
`Provider "/usr/local/lib/libwindowsfidobridge.so" implements unsupported version 0x00050000 (supported: 0x00040000)`

I'm running Ubuntu 20.04.1 LTS, but I would expect it to be compatible with similar instructions as Debian mentioned in the README..

I'm not sure how to go about diagnosing, but happy to give any output if it's helpful.
```
MYLAPTOP:~%>ssh -V
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

COGRNETAL382ZR7:~%>uname -a
Linux MYLAPTOP 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

MYLAPTOP:~%>lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

**Comment by mgbowen** [comment]
I probably should mention this in the README: the minimum supported version of OpenSSH is 8.3, unfortunately. OpenSSH 8.2 supports FIDO2/U2F keys, but there is an incompatibility between the data it passes to security key middlewares and Microsoft's WebAuthn API. Specifically, OpenSSH 8.2 passes a challenge string to be signed by the security key _after_ it's been hashed, but Microsoft's API requires that the challenge string be passed to it _before_ it's hashed. You can see an email thread on OpenSSH's mailing list discussing the change [here](https://marc.info/?l=openssh-unix-dev&m=158851596512060&w=2).

If there aren't any incompatibilities, you may find it fruitful to try pulling OpenSSH 8.3 from Ubuntu's groovy repos, though be aware that mixing releases can lead to lots of weirdness.

**Comment by schmitmd** [comment]
Compiled 8.3p1 from source with --prefix=/usr/local (to isolate from apt packaged ssh).
Worked like a _charm_.  Thank you so much!!
Would you like me to add this to the README and make a PR?

**Comment by mgbowen** [comment]
Glad to hear!

No worries about the PR, currently working on updating the README, I'll have a commit out soon 😀
