### ISSUE TITLE
Windows Defender detects the build output as Trojan:Win32/Fuery.C!cl

### ISSUE THREAD

**Issue by bluecmd** [mgbowen/windows-fido-bridge#5]
Hi,

I am building the FIDO bridge using Ubuntu 20.04 under WSL. During the `make -j $(nproc)` stage Windows Defender quarantines one of the files and alerts me it has found a threat.

![image](https://user-images.githubusercontent.com/149442/92234101-bf0ace80-eeb1-11ea-8dd0-98aa01970154.png)

I don't have any good suggestions on how to deal with this sadly.

**Comment by mgbowen** [comment]
Interesting. Unfortunately, I also don't have any good suggestions other than excluding the build directory from Windows Defender or using the apt repository I maintain at apt.mgbowen.dev (though I totally understand if you want to only compile from source for security or other reasons).

**Comment by bluecmd** [comment]
I looked around a bit and it seems quite common when using CMake - apparently the fact that the binary created is `a.exe` is part of the signal (!!). Anyway, the build worked anyway as it seems to have been only some build test binary and didn't actually have to run.

**Comment by mgbowen** [comment]
Glad to hear you were able to get it working! I'm going to go ahead and close this for now; feel free to reopen it or file another issue if you run into any other problems.
